version: "3.8"

services:

  db:
    image: postgres:15
    container_name: inkflow_db
    environment:
      POSTGRES_DB: blog_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1985
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./blogapp
    container_name: inkflow_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/blog_app
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1985
    ports:
      - "8080:8080"

  frontend:
    build: ./blog-frontend
    container_name: inkflow_frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  pgdata:
